name: Python Lib Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    uses: zepben/.github/.github/workflows/python-build.yml@main
    with:
      private: false
      licencecheck: true
    secrets: inherit

